version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chat-redis
    restart: always
    ports:
      - "36379:6379"
    volumes:
      - redisdata:/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: chat-pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@local.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"

  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: chat-redis-commander
  #   restart: always
  #   environment:
  #     REDIS_HOSTS: local:chat-redis:6379
  #   ports:
  #     - "8081:8081"

volumes:
  pgdata:
  redisdata:
